### ISSUE TITLE
Doesn't Work with MCA

### ISSUE THREAD

**Issue by KingDiamondZone** [CAD97/SpawnerCraft#8] opened 2016-10-26 00:49 UTC
Tried harvesting villagers in Minecraft Comes Alive in order to create a villager spawner. However, after killing at least 30 villagers, not one villager essence was dropped. I assume it's MCA, though there is the possibility that it's something else. Not necessarily an issue, just something to take note of.

**Comment by CAD97** [comment] 2016-10-26 18:30
Thanks for reporting this; I'll definitely take a look.

Just two things to double check which may be intended behavior:
- Are you using the Mob Fishing Rod?
- Do the villagers have a Spawn Egg?

I'll take a look as soon as I get a chance, but unfortunately I don't have much time right now in which to do so.

**Comment by KingDiamondZone** [comment] 2016-10-26 20:22
I can guarantee that I was using the mob fishing rod. And I can say that the villager spirit does exist, I used it to create a spawner in creative mode, but I wasn't able to get essence in Survival.

**Comment by CAD97** [comment] 2016-10-26 22:46
Definitely interesting. So the essence is getting registered but the drops are not getting handled. I think I know what may be causing this.

**Comment by CAD97** [comment] 2016-11-12 06:23
This is an interesting case: MCA does something a little weird.

MCA "villagers" are `MCA.EntityHuman`. On its own, this isn't strange. However, what is strange is that that entity doesn't have a spawn egg itself: you're expected to just spawn the Villager which MCA replaces with its own entity.

Thus, I never got to say "hey a Villager dies, drop a villager essence" as a villager never dies. I've added a override for `MCA.EntityHuman` (and took the opportunity to clean up my special case code), since this is a special case and a requested case.

I'm uploading 3.3 which fixes the issue.

However, for other people: I will only add an override in very limited cases. It needs to be spawn-able via a vanilla spawn egg. If it's via a Forge Egg, it should already work, and if it's been done custom, I don't have the wherewithal to support it.

**Comment by CAD97** [comment] 2017-06-15 19:53
Whoops, just realized I regressed this sometime between the fix and 4.0; I'm reopening to track the (re)fix.

**Comment by CAD97** [comment] 2017-06-15 21:45
The new commit allows you to specify something in `spawnercraft.cfg` like this:

```cfg
"egg mapping" {
    S:"minecraft:villager"=minecraft:zombie
}
```

This means that any time that you kill a `minecraft:villager`, instead attempt to drop the essence for `minecraft:zombie`.

I've yet to back-port this back to 1.10 (or even check if it's necessary; I'm focusing on version 4.0 for now), so I can't check how this would interact with MCA. I suspect we'll end up with an override something like this:

```cfg
"egg mapping" {
    S:"mca:human"=minecraft:villager
}
```

but of course it depends on how the MCA entities are named.

If/When MCA pushes a 1.11 version I will see if I can add it such that a newly generated `spawnercraft.cfg` will contain an override for MCA's human mob.

**Comment by CAD97** [comment] 2017-06-15 21:45
I'm closing this for now as with the next beta release you will be able to add custom overrides as above.

**Closed as completed by CAD97** 2017-06-15 21:45 UTC
Labels: bug
